---
title: "'financr' Ecosystem"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{'financr' Ecosystem}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Other `'R packages'` retrieves data from Yahoo Finance, and thus have the same source as `'financr'`, e.g., [`'yahoofinancer'`](https://cran.r-project.org/package=yahoofinancer), [`'quantmod'`](https://cran.r-project.org/package=quantmod). The same is true for packages that depends on them, e.g., [`'yfr'`](https://cran.r-project.org/package=yfR) and [`'stocks'`](https://cran.r-project.org/package=stocks) that depends on `'quantmod'`. 

`'financr'` only retrieves data from Yahoo Finance, without assumptions about the visualizations or analyses performed with these financial data. Consequently, `'financr'` dependencies are kept low, while other packages sometimes offers more advanced methods. For example, `'quantmod'` offers financial data-analysis oriented functions and time series data visualization methods.

Regarding the fetching of historical data from Yahoo Finance API,

- `financr::get_historic()` return a standard `data.frame` ;
- `'yahoofinancer'` methods return an `'R6'` class object (e.g., `Ticker$get_history`) ;
- `quantmod::getSymbols()` return a `'xts'` & `'zoo'` time series object ;
- `yfr::yf_get()` return a tibble. 

`'financr'` functions always return a standardized `data.frame`, see the [Vignette 'Summary of financr Functions'](https://clement-lvd.github.io/financr/articles/Functions_summary.html). 
